sudo: required

services:
  - docker

script:
  - chmod +x build.sh && docker run -it  -v /var/run/docker.sock:/var/run/docker.sock -v ${PWD}:/src danielmunchcko/dotnet-mono-aws:2.1.302-mono-5.12.0.301-aws-1.15.65 /bin/bash -c './build.sh -t "Deploy" ; ls tools; mono ./tools/GitVersion.CommandLine.3.6.5/tools/GitVersion.exe'

# Travis CI clones repositories to a depth of 50 commits, which breaks the GitVersion..

git:
  depth: false

# language: csharp

# # .NET CLI require Ubuntu 14.04
# sudo: false

# mono: 4.4.2

# # Ignore tagged commits
# if: tag IS blank

# script:
#   - chmod +x build.sh && ./build.sh -t "Deploy"

# cache:
#   directories:
#     - .packages
#     - tools/Addins
#     - tools/GitVersion.CommandLine