language: csharp

# .NET CLI require Ubuntu 14.04
sudo: false
dist: trusty

dotnet: 2.1.0

# Ignore tagged commits
if: tag IS blank

script:
  - chmod +x build.sh && ./build.sh -t "Deploy"

cache:
  directories:
    - .packages
    - tools/Addins
    - tools/GitVersion.CommandLine