# common configuration for ALL branches
image: ubuntu1804

test: off
cache:
- tools -> build.cake

build_script:
  - sh: chmod +x build.sh && docker run -v /var/run/docker.sock:/var/run/docker.sock -v ${PWD}:/src danielmunchcko/dotnet-mono-aws:2.0.5-sdk-2.1.4-mono-5.4.1.7-aws-1.14.32 ./build.sh -t "Deploy"

artifacts:
  - path: 'artifacts\*.nupkg'